// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAddYj3sNKyMeaGt2qe09JFZWY77PA1ufk',
    appId: '1:722222950412:web:6ad840ddaf73e0d9d1e629',
    messagingSenderId: '722222950412',
    projectId: 'machinetesttechware',
    authDomain: 'machinetesttechware.firebaseapp.com',
    storageBucket: 'machinetesttechware.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKjBhj54H8WMGpTB7bHgHGzv4nRzCGuI',
    appId: '1:722222950412:android:7b5d2b917eeac072d1e629',
    messagingSenderId: '722222950412',
    projectId: 'machinetesttechware',
    storageBucket: 'machinetesttechware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOucvRXC5yMxkyyGt-Z8Nnvue8MqfrDI',
    appId: '1:722222950412:ios:c33c0301fb894737d1e629',
    messagingSenderId: '722222950412',
    projectId: 'machinetesttechware',
    storageBucket: 'machinetesttechware.appspot.com',
    iosBundleId: 'com.example.machineTestTechware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPOucvRXC5yMxkyyGt-Z8Nnvue8MqfrDI',
    appId: '1:722222950412:ios:1de3d77722663b55d1e629',
    messagingSenderId: '722222950412',
    projectId: 'machinetesttechware',
    storageBucket: 'machinetesttechware.appspot.com',
    iosBundleId: 'com.example.machineTestTechware.RunnerTests',
  );
}
